import { style } from '@mui/system'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
 
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Notes
        </h1>

        <ul className={styles.posts}>
            <li>
              <p className={styles.postContent}>
              Thank you for filling out the application form. 
              </p>
              <p className={styles.postDate}>
                27/04/22
              </p>
            </li>

            <li>
            <p className={styles.postContent}>
              Thank you for filling out the application form. 
              </p>
              <p className={styles.postDate}>
                27/04/22
              </p>
            </li>

              <li>
              <p className={styles.postContent}>
              Thank you for filling out the application form. 
              </p>
              <p className={styles.postDate}>
                27/04/22
              </p>
            </li>
        </ul>
        <form>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formButton}>Add new note</button>
        </form>

      </main>
    </div>
  )
}
